// Map-of-content generator: build vault/index.md deterministically from every note's frontmatter
// `summary` (+ tags). Pure code, no LLM — a map-of-content is just a structured read over the corpus,
// exactly the kind of thing the READ side does for free. Grouped by folder (the human browse axis),
// entity → domain → form order. Falls back to the H1 title when `summary` is absent, so it never
// breaks on a note that predates the field.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

export type NoteMeta = {
  path: string;
  folder: string; // top-level vault folder (people, health, ...) — the browse drawer
  slug: string; // folder/name, the linkable ID
  title: string; // H1
  summary: string; // frontmatter summary, else title
  type: string;
  tags: string[];
};

const CONTROL = new Set(["index.md", "hot.md", "log.md"]);
// Folder display order: entities, then domains, then forms, then anything user-defined.
const FOLDER_ORDER = [
  "people", "orgs", "holdings",
  "identity", "health", "finances", "work", "life", "projects",
  "events", "mistakes",
];

function frontmatter(raw: string): string {
  return raw.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? "";
}
function fmScalar(fm: string, key: string): string {
  return (fm.match(new RegExp(`^${key}:\\s*(.+)$`, "im"))?.[1] ?? "").trim().replace(/^["']|["']$/g, "");
}
function fmList(fm: string, key: string): string[] {
  const line = fm.match(new RegExp(`^${key}:\\s*\\[(.*?)\\]`, "im"))?.[1] ?? "";
  return line.split(",").map((s) => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith(".") || entry.startsWith("_")) continue; // dotfiles + _tags/_needs-review
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (entry.endsWith(".md") && !CONTROL.has(entry)) out.push(p);
  }
  return out;
}

export function collectNotes(vault: string): NoteMeta[] {
  const notes: NoteMeta[] = [];
  for (const path of walk(vault)) {
    const raw = readFileSync(path, "utf8");
    const fm = frontmatter(raw);
    const rel = relative(vault, path).split("\\").join("/");
    const folder = rel.includes("/") ? rel.slice(0, rel.indexOf("/")) : ".";
    const slug = rel.replace(/\.md$/, "");
    const title = raw.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? slug;
    const summary = fmScalar(fm, "summary") || title;
    notes.push({ path, folder, slug, title, summary, type: fmScalar(fm, "type"), tags: fmList(fm, "tags") });
  }
  return notes;
}

function folderRank(f: string): number {
  const i = FOLDER_ORDER.indexOf(f);
  return i < 0 ? FOLDER_ORDER.length : i;
}

// Build index.md and write it. Returns counts for the caller to report.
export function generateIndex(vault: string): { count: number; folders: number } {
  const notes = collectNotes(vault);
  const byFolder = new Map<string, NoteMeta[]>();
  for (const n of notes) {
    if (!byFolder.has(n.folder)) byFolder.set(n.folder, []);
    byFolder.get(n.folder)!.push(n);
  }
  const folders = [...byFolder.keys()].sort((a, b) => folderRank(a) - folderRank(b) || a.localeCompare(b));

  const lines: string[] = [
    "---",
    "type: index",
    "---",
    "",
    "# Index",
    "",
    `> Generated by \`imprint check\` — do not edit by hand. ${notes.length} notes across ${folders.length} folders.`,
    "",
  ];
  for (const f of folders) {
    const items = byFolder.get(f)!.sort((a, b) => a.slug.localeCompare(b.slug));
    lines.push(`## ${f}/  (${items.length})`, "");
    for (const n of items) {
      const tags = n.tags.length ? `  \`${n.tags.join("` `")}\`` : "";
      lines.push(`- [[${n.slug}]] — ${n.summary}${tags}`);
    }
    lines.push("");
  }
  writeFileSync(join(vault, "index.md"), lines.join("\n") + "\n");
  return { count: notes.length, folders: folders.length };
}
