// 03b item 4. Two runners, ONE server, proved by the server's own identity.
// (SPEC §1, D5, D-85, D-98)
//
// Check 17's residue, in RED-RUN-2's words: "Check 17's observation covers one
// server. It does not rule out an additional hidden store or a decoy named
// connection to the checked server, and `application_name` does not identify
// the originating operating-system process." What closes it is the runner
// saying, IN THE STORE, which server it believes it is connected to: one line
// at connect carrying `system_identifier` from `pg_control_system()`, which is
// the cluster's own identity and is generated by `initdb`. Two runners whose
// lines carry the same identifier were talking to the same cluster, and a line
// whose identifier is not the identifier of the store a `check` is reading is a
// row that was written against some other cluster.
//
// WHY THE LINE IS THE RUNNER'S OWN STREAM. The runner may not write stream
// `machine`: that is the hub's, fenced by `ledger_event_hub_writes`. So it is
// `stream = 'runner'`, `kind = 'connected'`, `actor = 'runner'`, subject the
// runner id, and the runner policy widens to carry it. ONE statement, at
// connect, which D-85 already allows and which lands long before any wait
// window opens, so `test/runner-drain.test.ts`'s zero-statement window is
// untouched.
//
// Red reasons. Test 1: behaviour absent, `src/runner/run.ts` writes nothing at
// connect, so `ledger_event` holds no `runner` stream at all and the two
// connected lines this asserts do not exist. Test 2: behaviour absent,
// `src/check/run.ts` has no `store-split` finding, so a planted pair of lines
// naming two different clusters is reported as nothing.

import { test, expect, beforeAll, afterAll } from "bun:test";
import {
  startCluster,
  seam,
  startReadySubprocess,
  until,
  type Cluster,
  type ReadyProcess,
} from "./helpers/cluster.ts";
import {
  AGENT2,
  CHAT,
  DOOR,
  PERSON,
  PERSON2,
  RUNNER2,
  insertInbound,
  plantChatLine,
  stageHub,
  superStore,
  type StagedHub,
} from "./helpers/hub-fixture.ts";
import type { Finding } from "./helpers/finding.ts";

const RUNNER_PI = "runner-pi";
const SLOW = 150_000;

let cluster: Cluster;

beforeAll(async () => {
  cluster = await startCluster();
});

afterAll(async () => {
  if (cluster) await cluster.stop();
});

/** The same two-machine registry check 17 uses, one agent per runner. */
async function stageTwoMachines(): Promise<StagedHub> {
  const it = await stageHub(cluster, {
    servers: true,
    machines: [
      { id: "pi", os: "linux" },
      { id: "mac", os: "macos" },
    ],
    people: [
      { id: PERSON, tree: "/var/lib/imprnt-hub/p1" },
      { id: PERSON2, tree: "/var/lib/imprnt-hub/p2" },
    ],
    hub: { shared_zone: "/var/lib/imprnt-hub/shared" },
    agents: [
      {
        id: AGENT2,
        person: PERSON2,
        preset: "daily",
        chat: `${CHAT}1`,
        door: DOOR,
        runner: RUNNER2,
      },
    ],
    run: [
      {
        id: DOOR,
        kind: "door",
        machine: "pi",
        platform: "fake",
        person: PERSON,
        token_file: "/dev/null",
        schedule: "always",
        memory_limit_mb: 192,
      },
      {
        id: RUNNER_PI,
        kind: "runner",
        machine: "pi",
        schedule: "always",
        memory_limit_mb: 512,
        child_memory_limit_mb: 512,
      },
      {
        id: RUNNER2,
        kind: "runner",
        machine: "mac",
        schedule: "always",
        memory_limit_mb: 512,
        child_memory_limit_mb: 2048,
      },
    ],
  });
  const text = await Bun.file(it.registryFile).text();
  await Bun.write(
    it.registryFile,
    text.replace(/runner = "runner-test"/, `runner = "${RUNNER_PI}"`),
  );
  return it;
}

function startRunner(it: StagedHub, id: string): Promise<ReadyProcess> {
  return startReadySubprocess("test/helpers/runner-subprocess.ts", [
    it.registryFile,
    id,
    it.adapterUrl,
    it.adapterName,
  ]);
}

test(
  "STORE-02 every runner says which server it reached: each one writes exactly ONE runner/connected line at connect, naming itself, the cluster's own system_identifier and the machine the registry says it runs on, both identifiers are the identifier of the one cluster this test started, and neither line is written again on any later tick (SPEC §1, D5, D-85, D-98)",
  async () => {
    const { runRunner } = await seam("src/runner/run.ts");
    expect(typeof runRunner).toBe("function");

    const it = await stageTwoMachines();
    let pi: ReadyProcess | null = null;
    let mac: ReadyProcess | null = null;
    try {
      plantChatLine({ stateDir: it.stateDir, text: "what was said yesterday" });
      plantChatLine({
        stateDir: it.stateDir,
        person: PERSON2,
        agent: AGENT2,
        text: "what the second person said yesterday",
      });

      pi = await startRunner(it, RUNNER_PI);
      mac = await startRunner(it, RUNNER2);

      // One message each, so both are past their connect and really working.
      await insertInbound(cluster, it.db, { id: "ss-1", body: "a message for the first agent" });
      await insertInbound(cluster, it.db, {
        id: "ss-2",
        body: "a message for the second agent",
        person: PERSON2,
        agent: AGENT2,
      });
      await until(
        "both agents answered",
        async () => (await it.read.outbox()).length >= 2,
        90_000,
        async () => JSON.stringify(await it.read.inbound()),
      );

      const connected = await it.read.ledger({ stream: "runner", kind: "connected" });
      expect(connected.map((row) => row.subject).sort()).toEqual([RUNNER2, RUNNER_PI].sort());
      for (const row of connected) expect(row.actor).toBe("runner");

      // --- THE SERVER'S OWN IDENTITY, which a test cannot forge and a runner
      //     cannot have invented: it is generated by `initdb` for this cluster.
      const [control] = (await it.read.sql(
        "select system_identifier::text as id, version() as version from pg_control_system()",
      )) as { id: string; version: string }[];
      expect(control.id.length).toBeGreaterThan(0);
      for (const row of connected) {
        expect(String(row.detail.system_identifier)).toBe(control.id);
        expect(String(row.detail.server_version).length).toBeGreaterThan(0);
      }
      // BOTH runners named the SAME one, which is the criterion.
      expect(new Set(connected.map((row) => String(row.detail.system_identifier))).size).toBe(1);

      // --- and each line knows which machine wrote it, so a household reading
      //     the diary can tell the two apart without a second file.
      const byRunner = new Map(connected.map((row) => [row.subject, row]));
      expect(String(byRunner.get(RUNNER_PI)!.detail.machine)).toBe("pi");
      expect(String(byRunner.get(RUNNER2)!.detail.machine)).toBe("mac");

      // --- ONE line each, still, after several ticks. A per-tick write would
      //     be a heartbeat, which is the exact thing D-85 refuses.
      const seq = Math.max(...connected.map((row) => row.seq));
      await Bun.sleep(6000);
      const again = await it.read.ledger({ stream: "runner", kind: "connected" });
      expect(again.length).toBe(2);
      expect(Math.max(...again.map((row) => row.seq))).toBe(seq);
    } finally {
      if (pi) await pi.stop();
      if (mac) await mac.stop();
      await it.stop();
    }
  },
  SLOW,
);

test(
  "SPEC §1 a runner that reached some other cluster is a finding: check reports store-split for the connected line whose system_identifier is not this store's own, names the runner and the two identifiers, carries the one-store instruction as text, and reports nothing at all for a pair that both name this cluster (SPEC §1, D5, L13)",
  async () => {
    const { runCheck } = await seam("src/check/run.ts");
    const check = runCheck as (options: Record<string, unknown>) => Promise<Finding[]>;

    const it = await stageTwoMachines();
    const store = await superStore(cluster, it.db);
    try {
      const [control] = (await it.read.sql(
        "select system_identifier::text as id from pg_control_system()",
      )) as { id: string }[];
      const elsewhere = "1234567890123456789";
      expect(elsewhere).not.toBe(control.id);

      // --- THE HONEST PAIR FIRST. Both lines name this cluster, which is what
      //     a household with one store looks like, and it is the control that
      //     stops the finding firing on the mere presence of two runners.
      const plant = async (runner: string, machine: string, identifier: string) => {
        await it.read.sql(
          `insert into ledger_event (stream, subject, kind, actor, detail)
           values ('runner', $1, 'connected', 'runner', $2::jsonb)`,
          [
            runner,
            JSON.stringify({
              system_identifier: identifier,
              server_version: "PostgreSQL 17.0",
              machine,
            }),
          ],
        );
      };
      await plant(RUNNER_PI, "pi", control.id);
      await plant(RUNNER2, "mac", control.id);

      const clean = await check({
        machine: "mac",
        registryFile: it.registryFile,
        store,
        os: null,
        kernel: null,
      });
      expect(clean.filter((one) => one.kind === "store-split")).toEqual([]);

      // --- AND THE SPLIT. A second store means rows that are not all in the
      //     same place, and the line that says so is the one whose identifier
      //     is not this cluster's.
      await plant(RUNNER2, "mac", elsewhere);
      const split = await check({
        machine: "mac",
        registryFile: it.registryFile,
        store,
        os: null,
        kernel: null,
      });
      const found = split.filter((one) => one.kind === "store-split");
      expect(found.length).toBe(1);
      expect(found[0].subject).toBe(RUNNER2);
      expect(found[0].machine).toBe("mac");
      expect(found[0].id).toBe(`mac/store-split:${RUNNER2}`);
      // It names the runner AND both identifiers, or nobody can tell which
      // half of the household is in the wrong place.
      expect(found[0].says).toContain(RUNNER2);
      expect(found[0].says).toContain(elsewhere);
      expect(found[0].says).toContain(control.id);
      // The fix is the one-store rule, as text. Nothing runs it.
      expect(found[0].fix).toContain("hub.store_url");
      expect(found[0].fix.length).toBeGreaterThan(0);
      // The runner that is where it should be is not reported.
      expect(found.map((one) => one.subject)).not.toContain(RUNNER_PI);

      // --- AND A RUNNER THAT NAMED NO SERVER AT ALL. An empty identifier used
      //     to be skipped without a word, which is the one value that cannot be
      //     told from a healthy runner: a runner that could not read the
      //     server's identity then pointed wherever it liked and `check` called
      //     the household clean. It is the same finding with a different
      //     reason, and the reason is the runner's own.
      const plantRaw = async (runner: string, detail: unknown) => {
        await it.read.sql(
          `insert into ledger_event (stream, subject, kind, actor, detail)
           values ('runner', $1, 'connected', 'runner', $2::jsonb)`,
          [runner, JSON.stringify(detail)],
        );
      };
      const denied = "reading pg_control_system() failed: permission denied";
      await plantRaw(RUNNER_PI, {
        system_identifier: "",
        server_version: "",
        machine: "pi",
        identifier_error: denied,
      });
      const mute = await check({
        machine: "mac",
        registryFile: it.registryFile,
        store,
        os: null,
        kernel: null,
      });
      const quiet = mute.filter((one) => one.kind === "store-split" && one.subject === RUNNER_PI);
      expect(quiet.length).toBe(1);
      // It carries the runner's OWN reason, so a household reads why rather
      // than being told to go and look.
      expect(quiet[0].says).toContain(denied);
      expect(quiet[0].fix).toContain("hub.store_url");
      // The runner that really is in the wrong place is still reported beside
      // it, so the silent one did not take its place.
      expect(mute.filter((one) => one.kind === "store-split").length).toBe(2);

      // --- AND A DETAIL IN AN ENCODING THIS READER DOES NOT UNDERSTAND, which
      //     is the shape a client upgrade could land tomorrow. It carries no
      //     reason to quote, so the finding supplies one rather than falling
      //     silent, which is what the whole item is about.
      await plantRaw(RUNNER_PI, "not a detail this reader understands");
      const strange = await check({
        machine: "mac",
        registryFile: it.registryFile,
        store,
        os: null,
        kernel: null,
      });
      const odd = strange.filter((one) => one.kind === "store-split" && one.subject === RUNNER_PI);
      expect(odd.length).toBe(1);
      expect(odd[0].says).toContain(RUNNER_PI);
      expect(odd[0].says.length).toBeGreaterThan(0);
      expect(odd[0].fix).toContain("hub.store_url");
    } finally {
      await store.close().catch(() => {});
      await it.stop();
    }
  },
  SLOW,
);
